package org.oasis.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.oasis.model.CsCase;
import org.oasis.model.CsCaseExample;

public interface CsCaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_case
     *
     * @mbg.generated
     */
    long countByExample(CsCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_case
     *
     * @mbg.generated
     */
    int deleteByExample(CsCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_case
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_case
     *
     * @mbg.generated
     */
    int insert(CsCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_case
     *
     * @mbg.generated
     */
    int insertSelective(CsCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_case
     *
     * @mbg.generated
     */
    List<CsCase> selectByExample(CsCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_case
     *
     * @mbg.generated
     */
    CsCase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_case
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CsCase record, @Param("example") CsCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_case
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CsCase record, @Param("example") CsCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_case
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CsCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_case
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CsCase record);
}