package org.oasis.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.oasis.model.CsOvdReason;
import org.oasis.model.CsOvdReasonExample;

public interface CsOvdReasonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_ovd_reason
     *
     * @mbg.generated
     */
    long countByExample(CsOvdReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_ovd_reason
     *
     * @mbg.generated
     */
    int deleteByExample(CsOvdReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_ovd_reason
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_ovd_reason
     *
     * @mbg.generated
     */
    int insert(CsOvdReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_ovd_reason
     *
     * @mbg.generated
     */
    int insertSelective(CsOvdReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_ovd_reason
     *
     * @mbg.generated
     */
    List<CsOvdReason> selectByExample(CsOvdReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_ovd_reason
     *
     * @mbg.generated
     */
    CsOvdReason selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_ovd_reason
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CsOvdReason record, @Param("example") CsOvdReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_ovd_reason
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CsOvdReason record, @Param("example") CsOvdReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_ovd_reason
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CsOvdReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_ovd_reason
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CsOvdReason record);
}