package org.oasis.model;

import java.io.Serializable;

public class CsCase implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.batch_id
     *
     * @mbg.generated
     */
    private Integer batchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.rule_id
     *
     * @mbg.generated
     */
    private Integer ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.mifi_id
     *
     * @mbg.generated
     */
    private Long mifiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.flag
     *
     * @mbg.generated
     */
    private Integer flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.days
     *
     * @mbg.generated
     */
    private Integer days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.amount
     *
     * @mbg.generated
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.ovd_prin
     *
     * @mbg.generated
     */
    private Long ovdPrin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.ovd_interest
     *
     * @mbg.generated
     */
    private Long ovdInterest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.ovd_prin_pena
     *
     * @mbg.generated
     */
    private Long ovdPrinPena;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.ovd_interest_pena
     *
     * @mbg.generated
     */
    private Long ovdInterestPena;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.paid_ovd_prin
     *
     * @mbg.generated
     */
    private Long paidOvdPrin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.paid_ovd_interest
     *
     * @mbg.generated
     */
    private Long paidOvdInterest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.paid_ovd_prin_pena
     *
     * @mbg.generated
     */
    private Long paidOvdPrinPena;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.paid_ovd_interest_pena
     *
     * @mbg.generated
     */
    private Long paidOvdInterestPena;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.yesterday_repay
     *
     * @mbg.generated
     */
    private Long yesterdayRepay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.total_repay
     *
     * @mbg.generated
     */
    private Long totalRepay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.used_amount
     *
     * @mbg.generated
     */
    private Long usedAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.loan_purpose
     *
     * @mbg.generated
     */
    private String loanPurpose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.task_id
     *
     * @mbg.generated
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.assignee
     *
     * @mbg.generated
     */
    private String assignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.contact_info_status
     *
     * @mbg.generated
     */
    private Integer contactInfoStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.task_delegate_status
     *
     * @mbg.generated
     */
    private Integer taskDelegateStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.queue_type
     *
     * @mbg.generated
     */
    private Integer queueType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.queue_time
     *
     * @mbg.generated
     */
    private Long queueTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.customer_flag
     *
     * @mbg.generated
     */
    private String customerFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.overdue_count
     *
     * @mbg.generated
     */
    private Integer overdueCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.repayment_count
     *
     * @mbg.generated
     */
    private Integer repaymentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.orgn_id
     *
     * @mbg.generated
     */
    private String orgnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.assign_time
     *
     * @mbg.generated
     */
    private Long assignTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.return_time
     *
     * @mbg.generated
     */
    private Long returnTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.notice
     *
     * @mbg.generated
     */
    private String notice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.notice_operator
     *
     * @mbg.generated
     */
    private String noticeOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.notice_update_time
     *
     * @mbg.generated
     */
    private Long noticeUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.ovd_fee
     *
     * @mbg.generated
     */
    private Long ovdFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.paid_ovd_fee
     *
     * @mbg.generated
     */
    private Long paidOvdFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.repayment_day
     *
     * @mbg.generated
     */
    private Integer repaymentDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.first_assign_time
     *
     * @mbg.generated
     */
    private Long firstAssignTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.case_end_time
     *
     * @mbg.generated
     */
    private Long caseEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.ovd_start_time
     *
     * @mbg.generated
     */
    private Long ovdStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.channel
     *
     * @mbg.generated
     */
    private Integer channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.case_type
     *
     * @mbg.generated
     */
    private Short caseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.age_month
     *
     * @mbg.generated
     */
    private Integer ageMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.ovd_principal
     *
     * @mbg.generated
     */
    private Long ovdPrincipal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.ovd_interest_fee
     *
     * @mbg.generated
     */
    private Long ovdInterestFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.paid_ovd_principal
     *
     * @mbg.generated
     */
    private Long paidOvdPrincipal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_case.paid_ovd_interest_fee
     *
     * @mbg.generated
     */
    private Long paidOvdInterestFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_case
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.id
     *
     * @return the value of cs_case.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.id
     *
     * @param id the value for cs_case.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.batch_id
     *
     * @return the value of cs_case.batch_id
     *
     * @mbg.generated
     */
    public Integer getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.batch_id
     *
     * @param batchId the value for cs_case.batch_id
     *
     * @mbg.generated
     */
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.rule_id
     *
     * @return the value of cs_case.rule_id
     *
     * @mbg.generated
     */
    public Integer getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.rule_id
     *
     * @param ruleId the value for cs_case.rule_id
     *
     * @mbg.generated
     */
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.mifi_id
     *
     * @return the value of cs_case.mifi_id
     *
     * @mbg.generated
     */
    public Long getMifiId() {
        return mifiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.mifi_id
     *
     * @param mifiId the value for cs_case.mifi_id
     *
     * @mbg.generated
     */
    public void setMifiId(Long mifiId) {
        this.mifiId = mifiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.code
     *
     * @return the value of cs_case.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.code
     *
     * @param code the value for cs_case.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.level
     *
     * @return the value of cs_case.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.level
     *
     * @param level the value for cs_case.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.flag
     *
     * @return the value of cs_case.flag
     *
     * @mbg.generated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.flag
     *
     * @param flag the value for cs_case.flag
     *
     * @mbg.generated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.days
     *
     * @return the value of cs_case.days
     *
     * @mbg.generated
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.days
     *
     * @param days the value for cs_case.days
     *
     * @mbg.generated
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.amount
     *
     * @return the value of cs_case.amount
     *
     * @mbg.generated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.amount
     *
     * @param amount the value for cs_case.amount
     *
     * @mbg.generated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.ovd_prin
     *
     * @return the value of cs_case.ovd_prin
     *
     * @mbg.generated
     */
    public Long getOvdPrin() {
        return ovdPrin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.ovd_prin
     *
     * @param ovdPrin the value for cs_case.ovd_prin
     *
     * @mbg.generated
     */
    public void setOvdPrin(Long ovdPrin) {
        this.ovdPrin = ovdPrin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.ovd_interest
     *
     * @return the value of cs_case.ovd_interest
     *
     * @mbg.generated
     */
    public Long getOvdInterest() {
        return ovdInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.ovd_interest
     *
     * @param ovdInterest the value for cs_case.ovd_interest
     *
     * @mbg.generated
     */
    public void setOvdInterest(Long ovdInterest) {
        this.ovdInterest = ovdInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.ovd_prin_pena
     *
     * @return the value of cs_case.ovd_prin_pena
     *
     * @mbg.generated
     */
    public Long getOvdPrinPena() {
        return ovdPrinPena;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.ovd_prin_pena
     *
     * @param ovdPrinPena the value for cs_case.ovd_prin_pena
     *
     * @mbg.generated
     */
    public void setOvdPrinPena(Long ovdPrinPena) {
        this.ovdPrinPena = ovdPrinPena;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.ovd_interest_pena
     *
     * @return the value of cs_case.ovd_interest_pena
     *
     * @mbg.generated
     */
    public Long getOvdInterestPena() {
        return ovdInterestPena;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.ovd_interest_pena
     *
     * @param ovdInterestPena the value for cs_case.ovd_interest_pena
     *
     * @mbg.generated
     */
    public void setOvdInterestPena(Long ovdInterestPena) {
        this.ovdInterestPena = ovdInterestPena;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.paid_ovd_prin
     *
     * @return the value of cs_case.paid_ovd_prin
     *
     * @mbg.generated
     */
    public Long getPaidOvdPrin() {
        return paidOvdPrin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.paid_ovd_prin
     *
     * @param paidOvdPrin the value for cs_case.paid_ovd_prin
     *
     * @mbg.generated
     */
    public void setPaidOvdPrin(Long paidOvdPrin) {
        this.paidOvdPrin = paidOvdPrin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.paid_ovd_interest
     *
     * @return the value of cs_case.paid_ovd_interest
     *
     * @mbg.generated
     */
    public Long getPaidOvdInterest() {
        return paidOvdInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.paid_ovd_interest
     *
     * @param paidOvdInterest the value for cs_case.paid_ovd_interest
     *
     * @mbg.generated
     */
    public void setPaidOvdInterest(Long paidOvdInterest) {
        this.paidOvdInterest = paidOvdInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.paid_ovd_prin_pena
     *
     * @return the value of cs_case.paid_ovd_prin_pena
     *
     * @mbg.generated
     */
    public Long getPaidOvdPrinPena() {
        return paidOvdPrinPena;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.paid_ovd_prin_pena
     *
     * @param paidOvdPrinPena the value for cs_case.paid_ovd_prin_pena
     *
     * @mbg.generated
     */
    public void setPaidOvdPrinPena(Long paidOvdPrinPena) {
        this.paidOvdPrinPena = paidOvdPrinPena;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.paid_ovd_interest_pena
     *
     * @return the value of cs_case.paid_ovd_interest_pena
     *
     * @mbg.generated
     */
    public Long getPaidOvdInterestPena() {
        return paidOvdInterestPena;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.paid_ovd_interest_pena
     *
     * @param paidOvdInterestPena the value for cs_case.paid_ovd_interest_pena
     *
     * @mbg.generated
     */
    public void setPaidOvdInterestPena(Long paidOvdInterestPena) {
        this.paidOvdInterestPena = paidOvdInterestPena;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.yesterday_repay
     *
     * @return the value of cs_case.yesterday_repay
     *
     * @mbg.generated
     */
    public Long getYesterdayRepay() {
        return yesterdayRepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.yesterday_repay
     *
     * @param yesterdayRepay the value for cs_case.yesterday_repay
     *
     * @mbg.generated
     */
    public void setYesterdayRepay(Long yesterdayRepay) {
        this.yesterdayRepay = yesterdayRepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.total_repay
     *
     * @return the value of cs_case.total_repay
     *
     * @mbg.generated
     */
    public Long getTotalRepay() {
        return totalRepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.total_repay
     *
     * @param totalRepay the value for cs_case.total_repay
     *
     * @mbg.generated
     */
    public void setTotalRepay(Long totalRepay) {
        this.totalRepay = totalRepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.used_amount
     *
     * @return the value of cs_case.used_amount
     *
     * @mbg.generated
     */
    public Long getUsedAmount() {
        return usedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.used_amount
     *
     * @param usedAmount the value for cs_case.used_amount
     *
     * @mbg.generated
     */
    public void setUsedAmount(Long usedAmount) {
        this.usedAmount = usedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.loan_purpose
     *
     * @return the value of cs_case.loan_purpose
     *
     * @mbg.generated
     */
    public String getLoanPurpose() {
        return loanPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.loan_purpose
     *
     * @param loanPurpose the value for cs_case.loan_purpose
     *
     * @mbg.generated
     */
    public void setLoanPurpose(String loanPurpose) {
        this.loanPurpose = loanPurpose == null ? null : loanPurpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.task_id
     *
     * @return the value of cs_case.task_id
     *
     * @mbg.generated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.task_id
     *
     * @param taskId the value for cs_case.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.assignee
     *
     * @return the value of cs_case.assignee
     *
     * @mbg.generated
     */
    public String getAssignee() {
        return assignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.assignee
     *
     * @param assignee the value for cs_case.assignee
     *
     * @mbg.generated
     */
    public void setAssignee(String assignee) {
        this.assignee = assignee == null ? null : assignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.remark
     *
     * @return the value of cs_case.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.remark
     *
     * @param remark the value for cs_case.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.contact_info_status
     *
     * @return the value of cs_case.contact_info_status
     *
     * @mbg.generated
     */
    public Integer getContactInfoStatus() {
        return contactInfoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.contact_info_status
     *
     * @param contactInfoStatus the value for cs_case.contact_info_status
     *
     * @mbg.generated
     */
    public void setContactInfoStatus(Integer contactInfoStatus) {
        this.contactInfoStatus = contactInfoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.task_delegate_status
     *
     * @return the value of cs_case.task_delegate_status
     *
     * @mbg.generated
     */
    public Integer getTaskDelegateStatus() {
        return taskDelegateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.task_delegate_status
     *
     * @param taskDelegateStatus the value for cs_case.task_delegate_status
     *
     * @mbg.generated
     */
    public void setTaskDelegateStatus(Integer taskDelegateStatus) {
        this.taskDelegateStatus = taskDelegateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.status
     *
     * @return the value of cs_case.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.status
     *
     * @param status the value for cs_case.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.create_time
     *
     * @return the value of cs_case.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.create_time
     *
     * @param createTime the value for cs_case.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.update_time
     *
     * @return the value of cs_case.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.update_time
     *
     * @param updateTime the value for cs_case.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.queue_type
     *
     * @return the value of cs_case.queue_type
     *
     * @mbg.generated
     */
    public Integer getQueueType() {
        return queueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.queue_type
     *
     * @param queueType the value for cs_case.queue_type
     *
     * @mbg.generated
     */
    public void setQueueType(Integer queueType) {
        this.queueType = queueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.queue_time
     *
     * @return the value of cs_case.queue_time
     *
     * @mbg.generated
     */
    public Long getQueueTime() {
        return queueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.queue_time
     *
     * @param queueTime the value for cs_case.queue_time
     *
     * @mbg.generated
     */
    public void setQueueTime(Long queueTime) {
        this.queueTime = queueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.customer_flag
     *
     * @return the value of cs_case.customer_flag
     *
     * @mbg.generated
     */
    public String getCustomerFlag() {
        return customerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.customer_flag
     *
     * @param customerFlag the value for cs_case.customer_flag
     *
     * @mbg.generated
     */
    public void setCustomerFlag(String customerFlag) {
        this.customerFlag = customerFlag == null ? null : customerFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.overdue_count
     *
     * @return the value of cs_case.overdue_count
     *
     * @mbg.generated
     */
    public Integer getOverdueCount() {
        return overdueCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.overdue_count
     *
     * @param overdueCount the value for cs_case.overdue_count
     *
     * @mbg.generated
     */
    public void setOverdueCount(Integer overdueCount) {
        this.overdueCount = overdueCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.repayment_count
     *
     * @return the value of cs_case.repayment_count
     *
     * @mbg.generated
     */
    public Integer getRepaymentCount() {
        return repaymentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.repayment_count
     *
     * @param repaymentCount the value for cs_case.repayment_count
     *
     * @mbg.generated
     */
    public void setRepaymentCount(Integer repaymentCount) {
        this.repaymentCount = repaymentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.orgn_id
     *
     * @return the value of cs_case.orgn_id
     *
     * @mbg.generated
     */
    public String getOrgnId() {
        return orgnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.orgn_id
     *
     * @param orgnId the value for cs_case.orgn_id
     *
     * @mbg.generated
     */
    public void setOrgnId(String orgnId) {
        this.orgnId = orgnId == null ? null : orgnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.age
     *
     * @return the value of cs_case.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.age
     *
     * @param age the value for cs_case.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.assign_time
     *
     * @return the value of cs_case.assign_time
     *
     * @mbg.generated
     */
    public Long getAssignTime() {
        return assignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.assign_time
     *
     * @param assignTime the value for cs_case.assign_time
     *
     * @mbg.generated
     */
    public void setAssignTime(Long assignTime) {
        this.assignTime = assignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.return_time
     *
     * @return the value of cs_case.return_time
     *
     * @mbg.generated
     */
    public Long getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.return_time
     *
     * @param returnTime the value for cs_case.return_time
     *
     * @mbg.generated
     */
    public void setReturnTime(Long returnTime) {
        this.returnTime = returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.notice
     *
     * @return the value of cs_case.notice
     *
     * @mbg.generated
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.notice
     *
     * @param notice the value for cs_case.notice
     *
     * @mbg.generated
     */
    public void setNotice(String notice) {
        this.notice = notice == null ? null : notice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.notice_operator
     *
     * @return the value of cs_case.notice_operator
     *
     * @mbg.generated
     */
    public String getNoticeOperator() {
        return noticeOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.notice_operator
     *
     * @param noticeOperator the value for cs_case.notice_operator
     *
     * @mbg.generated
     */
    public void setNoticeOperator(String noticeOperator) {
        this.noticeOperator = noticeOperator == null ? null : noticeOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.notice_update_time
     *
     * @return the value of cs_case.notice_update_time
     *
     * @mbg.generated
     */
    public Long getNoticeUpdateTime() {
        return noticeUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.notice_update_time
     *
     * @param noticeUpdateTime the value for cs_case.notice_update_time
     *
     * @mbg.generated
     */
    public void setNoticeUpdateTime(Long noticeUpdateTime) {
        this.noticeUpdateTime = noticeUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.ovd_fee
     *
     * @return the value of cs_case.ovd_fee
     *
     * @mbg.generated
     */
    public Long getOvdFee() {
        return ovdFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.ovd_fee
     *
     * @param ovdFee the value for cs_case.ovd_fee
     *
     * @mbg.generated
     */
    public void setOvdFee(Long ovdFee) {
        this.ovdFee = ovdFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.paid_ovd_fee
     *
     * @return the value of cs_case.paid_ovd_fee
     *
     * @mbg.generated
     */
    public Long getPaidOvdFee() {
        return paidOvdFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.paid_ovd_fee
     *
     * @param paidOvdFee the value for cs_case.paid_ovd_fee
     *
     * @mbg.generated
     */
    public void setPaidOvdFee(Long paidOvdFee) {
        this.paidOvdFee = paidOvdFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.repayment_day
     *
     * @return the value of cs_case.repayment_day
     *
     * @mbg.generated
     */
    public Integer getRepaymentDay() {
        return repaymentDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.repayment_day
     *
     * @param repaymentDay the value for cs_case.repayment_day
     *
     * @mbg.generated
     */
    public void setRepaymentDay(Integer repaymentDay) {
        this.repaymentDay = repaymentDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.first_assign_time
     *
     * @return the value of cs_case.first_assign_time
     *
     * @mbg.generated
     */
    public Long getFirstAssignTime() {
        return firstAssignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.first_assign_time
     *
     * @param firstAssignTime the value for cs_case.first_assign_time
     *
     * @mbg.generated
     */
    public void setFirstAssignTime(Long firstAssignTime) {
        this.firstAssignTime = firstAssignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.case_end_time
     *
     * @return the value of cs_case.case_end_time
     *
     * @mbg.generated
     */
    public Long getCaseEndTime() {
        return caseEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.case_end_time
     *
     * @param caseEndTime the value for cs_case.case_end_time
     *
     * @mbg.generated
     */
    public void setCaseEndTime(Long caseEndTime) {
        this.caseEndTime = caseEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.ovd_start_time
     *
     * @return the value of cs_case.ovd_start_time
     *
     * @mbg.generated
     */
    public Long getOvdStartTime() {
        return ovdStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.ovd_start_time
     *
     * @param ovdStartTime the value for cs_case.ovd_start_time
     *
     * @mbg.generated
     */
    public void setOvdStartTime(Long ovdStartTime) {
        this.ovdStartTime = ovdStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.channel
     *
     * @return the value of cs_case.channel
     *
     * @mbg.generated
     */
    public Integer getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.channel
     *
     * @param channel the value for cs_case.channel
     *
     * @mbg.generated
     */
    public void setChannel(Integer channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.name
     *
     * @return the value of cs_case.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.name
     *
     * @param name the value for cs_case.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.case_type
     *
     * @return the value of cs_case.case_type
     *
     * @mbg.generated
     */
    public Short getCaseType() {
        return caseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.case_type
     *
     * @param caseType the value for cs_case.case_type
     *
     * @mbg.generated
     */
    public void setCaseType(Short caseType) {
        this.caseType = caseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.age_month
     *
     * @return the value of cs_case.age_month
     *
     * @mbg.generated
     */
    public Integer getAgeMonth() {
        return ageMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.age_month
     *
     * @param ageMonth the value for cs_case.age_month
     *
     * @mbg.generated
     */
    public void setAgeMonth(Integer ageMonth) {
        this.ageMonth = ageMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.ovd_principal
     *
     * @return the value of cs_case.ovd_principal
     *
     * @mbg.generated
     */
    public Long getOvdPrincipal() {
        return ovdPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.ovd_principal
     *
     * @param ovdPrincipal the value for cs_case.ovd_principal
     *
     * @mbg.generated
     */
    public void setOvdPrincipal(Long ovdPrincipal) {
        this.ovdPrincipal = ovdPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.ovd_interest_fee
     *
     * @return the value of cs_case.ovd_interest_fee
     *
     * @mbg.generated
     */
    public Long getOvdInterestFee() {
        return ovdInterestFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.ovd_interest_fee
     *
     * @param ovdInterestFee the value for cs_case.ovd_interest_fee
     *
     * @mbg.generated
     */
    public void setOvdInterestFee(Long ovdInterestFee) {
        this.ovdInterestFee = ovdInterestFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.paid_ovd_principal
     *
     * @return the value of cs_case.paid_ovd_principal
     *
     * @mbg.generated
     */
    public Long getPaidOvdPrincipal() {
        return paidOvdPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.paid_ovd_principal
     *
     * @param paidOvdPrincipal the value for cs_case.paid_ovd_principal
     *
     * @mbg.generated
     */
    public void setPaidOvdPrincipal(Long paidOvdPrincipal) {
        this.paidOvdPrincipal = paidOvdPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_case.paid_ovd_interest_fee
     *
     * @return the value of cs_case.paid_ovd_interest_fee
     *
     * @mbg.generated
     */
    public Long getPaidOvdInterestFee() {
        return paidOvdInterestFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_case.paid_ovd_interest_fee
     *
     * @param paidOvdInterestFee the value for cs_case.paid_ovd_interest_fee
     *
     * @mbg.generated
     */
    public void setPaidOvdInterestFee(Long paidOvdInterestFee) {
        this.paidOvdInterestFee = paidOvdInterestFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_case
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", batchId=").append(batchId);
        sb.append(", ruleId=").append(ruleId);
        sb.append(", mifiId=").append(mifiId);
        sb.append(", code=").append(code);
        sb.append(", level=").append(level);
        sb.append(", flag=").append(flag);
        sb.append(", days=").append(days);
        sb.append(", amount=").append(amount);
        sb.append(", ovdPrin=").append(ovdPrin);
        sb.append(", ovdInterest=").append(ovdInterest);
        sb.append(", ovdPrinPena=").append(ovdPrinPena);
        sb.append(", ovdInterestPena=").append(ovdInterestPena);
        sb.append(", paidOvdPrin=").append(paidOvdPrin);
        sb.append(", paidOvdInterest=").append(paidOvdInterest);
        sb.append(", paidOvdPrinPena=").append(paidOvdPrinPena);
        sb.append(", paidOvdInterestPena=").append(paidOvdInterestPena);
        sb.append(", yesterdayRepay=").append(yesterdayRepay);
        sb.append(", totalRepay=").append(totalRepay);
        sb.append(", usedAmount=").append(usedAmount);
        sb.append(", loanPurpose=").append(loanPurpose);
        sb.append(", taskId=").append(taskId);
        sb.append(", assignee=").append(assignee);
        sb.append(", remark=").append(remark);
        sb.append(", contactInfoStatus=").append(contactInfoStatus);
        sb.append(", taskDelegateStatus=").append(taskDelegateStatus);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", queueType=").append(queueType);
        sb.append(", queueTime=").append(queueTime);
        sb.append(", customerFlag=").append(customerFlag);
        sb.append(", overdueCount=").append(overdueCount);
        sb.append(", repaymentCount=").append(repaymentCount);
        sb.append(", orgnId=").append(orgnId);
        sb.append(", age=").append(age);
        sb.append(", assignTime=").append(assignTime);
        sb.append(", returnTime=").append(returnTime);
        sb.append(", notice=").append(notice);
        sb.append(", noticeOperator=").append(noticeOperator);
        sb.append(", noticeUpdateTime=").append(noticeUpdateTime);
        sb.append(", ovdFee=").append(ovdFee);
        sb.append(", paidOvdFee=").append(paidOvdFee);
        sb.append(", repaymentDay=").append(repaymentDay);
        sb.append(", firstAssignTime=").append(firstAssignTime);
        sb.append(", caseEndTime=").append(caseEndTime);
        sb.append(", ovdStartTime=").append(ovdStartTime);
        sb.append(", channel=").append(channel);
        sb.append(", name=").append(name);
        sb.append(", caseType=").append(caseType);
        sb.append(", ageMonth=").append(ageMonth);
        sb.append(", ovdPrincipal=").append(ovdPrincipal);
        sb.append(", ovdInterestFee=").append(ovdInterestFee);
        sb.append(", paidOvdPrincipal=").append(paidOvdPrincipal);
        sb.append(", paidOvdInterestFee=").append(paidOvdInterestFee);
        sb.append("]");
        return sb.toString();
    }
}